# allowed-commands временно не работает
Ban:
 banReason:  Признание в читах #причина бана
 banDuration: 47 #время бана если игрок признался
 banQuit: лив с проверки #причина бана при выходе
 banquitday: 50 #время бана в днях
 Quit: true #банит при выходе с сервера
 BanCommand: litebans:ban #можно свою вписать команду для бана
 BanIgnore: Игнор проверки #причина бана игнора проверки
timer:
 time: 5 # Таймер в минутах
chat:
 allowed-commands:
  - "check"
  - "msg"
moder:
 allow:
  - '&7Модератор &e<moderator> &7закончил проверку игрока &e<target> &7и не обнаружил читов.'
 ignore:
  - '&7Модератор &e<moderator> &7закончил проверку игрока &e<target>. &7Игрок отказался от проверки.'
 dis:
  - '&7Модератор &e<moderator> &7закончил проверку игрока &e<target> &7и обнаружил читы. Игрок забанен.'
 check:
  - '&7Модератор &e<moderator> &7Вызвал игрока &e<target> &7на проверку на читы'
 message:
  - ''
  - '&c&l             ПРОВЕРКА'
  - '&f Вы подозреваетесь в использовании читов'
  - '&f     Проверяющим: &e<moderator>'
  - ''
  - '&f   У вас осталось <minutes> минут <seconds> секунд' # или <seconds>
  - ''
  - '&f  Выполните действия, указанные ниже'
  - '&f  -  Напишите ваш дискорд в чат'
  - '&f  -  Не выходите из игры'
  - ''
  - '&f  Ожидайте проверяющего в дискорде'
  - ''